### ISSUE TITLE
关于unet无法准确预测问题

### ISSUE THREAD

**Issue by Niccccci** [lsh1994/keras-segmentation#10]
首先感谢您的代码和教程，我先拿您的数据集和代码训练和预测都是正常的结果，但是改成自己的数据集之后train的acc总是在几乎1的数值且无法正确分割测试集中的图片，基本上测试结果为纯色，感觉没有学习到什么东西，请问您这可能是什么原因呢？我的数据集是500*500的，原图为png格式，标签为8位png的索引图，按照voc的颜色表制作的。提前感谢您的解答了。

**Comment by lsh1994** [comment]
一个比较常见的错误是， 预测结果是标签值（0，1，2）,直接（在看图应用上）看图（0-255）就是黑色的嗷，或许plt可视化效果好些。关于这个问题，请检查模型额输入和输出，以及是否为对应类别数量等

**Comment by Niccccci** [comment]
> 一个比较常见的错误是， 预测结果是标签值（0，1，2）,直接（在看图应用上）看图（0-255）就是黑色的嗷，或许plt可视化效果好些。关于这个问题，请检查模型额输入和输出，以及是否为对应类别数量等
感谢您的解答，另外我还有一个疑问跟您请教一下，一般对图像分割的效果衡量还有一个参数是meanIOU,您这边的这个acc指的是每个像素点预测的准确率吗？

**Comment by Niccccci** [comment]
感谢您的解答，我的预测结果不是黑色的，是彩色的，但是感觉没有正常预测图像。我还有一个疑问跟您请教一下，一般对图像分割的效果衡量还有一个参数是meanIOU,您这边的这个acc指的是每个像素点预测的准确率吗？另外在train文件中的类别数量是11，但是我打印您的label的索引值数量是0-11，这样的话类别数量不应该是12吗？在Unet模型文件中的类别和输入图像长宽类别也要根据自己的数据集改变吧？

**Comment by lsh1994** [comment]
是的。
visualizeDataset.py中类别设为了11，也可以设为别的。这一步你明白代码在干啥就行了。训练测试用的类别数是15。
一般自己的数据集都要**改输入输出什么的**。全卷积虽然可以输入任意长宽，但我们要组成batch，所以长宽是固定的。

代码仅是参考，很多不完善的地方，感觉不合理或有疑惑就改改看。🤣

**Comment by Niccccci** [comment]
十分感谢您的解答，我现在已经完成unet的训练了，之前无法训练是因为我的label图是彩色的8索引图，后来和您的数据集中的label统一格式之后就可以训练了。但是现在遇到了一个问题，我的train的loss先下降再趋于平稳，train的acc也一直升高再趋于平稳，但是val的loss和train一直上下波动，我用训练了300epoch的unet model去做predict，在test数据集上表现不是那么好，但是在train数据集上就分割的很好，这是遇到了过拟合的情况吧？我的数据集是320*320的，train中一共1500张左右，test中300多张，我觉得这个数据数量已经比较多了，请问您知道接下来我该做什么来改变这种过拟合的情况呢？
以下是我训练的曲线图。
![image](https://user-images.githubusercontent.com/34420634/55942172-68767200-5c76-11e9-9493-8aa5a9a3cc40.png)
![image](https://user-images.githubusercontent.com/34420634/55942194-762bf780-5c76-11e9-914b-07742c0f7194.png)
