### ISSUE TITLE
您好，请教一下utils.py的问题

### ISSUE THREAD

**Issue by kongnuonuo** [lsh1994/keras-segmentation#14]
非常感谢您分享代码，在学习您的代码时，我遇到了两个问题。
第一个是我在运行utils.py文件的时候，遇到错误

InvalidArgumentError (see above for traceback): indices[12] = [1, 5, 1, 0] does not index into shape [3,4,4,3]
	 [[{{node max_unpooling2d_1/max_unpooling2d_1/ScatterNd}} = ScatterNd[T=DT_FLOAT, Tindices=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](max_unpooling2d_1/max_unpooling2d_1/transpose, max_unpooling2d_1/max_unpooling2d_1/Reshape_2, max_unpooling2d_1/max_unpooling2d_1/ScatterNd/shape)]]

我没能从网上找到解决方法。（但是我运行SegNet网络时，没有任何问题）

第二个问题是关于K.tf的问题。 请问K.tf就相当于tensorflow吗？我做了几个实验，tensorflow中的函数都可以用K.tf实验，但是我没有在网上找到任何关于K.tf的资料

**Comment by lsh1994** [comment]
我运行了这个脚本，并没有出错。
是否是您的keras或tensorflow版本过高，可参考readme中说明。
据说tf.keras比keras api更高级更多，两者可以混合使用。具体可以搜搜官方说明: https://tensorflow.google.cn/guide/keras 。

**Comment by kongnuonuo** [comment]
感谢您的回复。我尝试了在 之前训练SegNet网络的电脑上运行这个脚本，确实没有出错。我两台电脑的库版本是一致的，具体问题我再找找吧。

关于第二个问题，我可能没有表达清楚，您在程序中使用的是keras.backend.tf。我想问的是keras.backend.tf是不是就等于tf了。我们可以在keras.backend.tf里使用任何tf里的函数。比如tf.constant就对应着keras.backend.tf.constant。
您给的链接已经失效了。

**Comment by kongnuonuo** [comment]
您好，脚本出错的原因我已经找到了。确实是我tensorflow版本的问题。在我运行出错的电脑上，我使用的是tensorflow1.11.0（非GPU版）。使用非GPU版本的tensorflow时，在调用K.tf.nn.max_pool_with_argmax函数时，计算索引时，是严格按照公式   (  (b * height + y)  *  width + x) * channels + c.计算的
其中：
在原图像中的索引：[b, y, x, c]
width：图像宽度，一般指input_shape[2]，对应x
height:图像高度，一般指input_shape[1]，对应y
channels：图像深度，一般指input_shape[3]

所以，在unpooling时，解析y和x的公式需要调整下。
而使用GPU版本时，根据我的猜想，它每个矩阵是分开来算的，所以b和c永远为0。

**Comment by alexbnlee** [comment]
目前还是报错，无法运行
keras: 2.4.3
tf: 2.4.0
