### ISSUE TITLE
getSegmentationArr 读取

### ISSUE THREAD

**Issue by ShaneShen** [lsh1994/keras-segmentation#3]
`    for c in range(nClasses):
        seg_labels[:, :, c] = (seg == c).astype(int)`
你好，我刚刚接触语义分割。我在getSegmentationArr函数下面看到的这段代码，我的理解是 c 是从0开始循环的，这样的话是不是背景也作为需要FCN网络来训练的一部分呢？

**Comment by lsh1994** [comment]
> ` for c in range(nClasses): seg_labels[:, :, c] = (seg == c).astype(int)`
> 你好，我刚刚接触语义分割。我在getSegmentationArr函数下面看到的这段代码，我的理解是 c 是从0开始循环的，这样的话是不是背景也作为需要FCN网络来训练的一部分呢？

背景也是一种标记
